### ISSUE TITLE
Reduce space and font size slightly in sidebars only

### ISSUE THREAD

**Issue by bergeson** [fsoe-asu/fultonSchoolsDiviTheme#12]
Example: http://move.engineering.asu.edu/poly/template-aviation/
Please reduce space between sidebar items and slightly reduce the widget/sidebar text size.
Compare to: 
http://poly.engineering.asu.edu/git/bs-graphic-information-technology/

**Comment by SteveRyan-ASU** [comment]
A little tougher than it sounded based the way that Divi handles the side bar content in mobile environments. But, I think this is closer to what you we were after. Features:
- Condensed and non-condensed look for sidebars can be toggled by adding the `.condensed` CSS to the Divi widget. Otherwise all applies styles for this fix will be ignored.
- Increased size of H3 globally to 1.8 rem. Sets it apart from the normal H4 tag which wasn't that much different.
- Divi Text widgets with the "condensed" tag applied to them will be treated as "sidebar-headers" and given an underline that connects with the normal sidebar's vertical line.
- adjusted spacing and padding in mobile views to match.

**Comment by SteveRyan-ASU** [comment]
## Desktop:

![2016-07-28_16-49-26](https://cloud.githubusercontent.com/assets/2085753/17233420/9402101a-54e4-11e6-92b7-0ba9bd563d5a.png)

**Comment by SteveRyan-ASU** [comment]
## Tablet-ish view 
Notice that widgets are aligned in a two col grid at this width.
![2016-07-28_16-48-34](https://cloud.githubusercontent.com/assets/2085753/17233422/95a47264-54e4-11e6-8744-af05b0c3bace.png)

**Comment by SteveRyan-ASU** [comment]
## Tablet View - kinda..

![2016-07-28_16-47-49](https://cloud.githubusercontent.com/assets/2085753/17233423/96ee92ee-54e4-11e6-8114-6cd2d7c2c213.png)

**Comment by SteveRyan-ASU** [comment]
## Mobile View

![2016-07-28_16-45-30](https://cloud.githubusercontent.com/assets/2085753/17233498/30f67122-54e5-11e6-85b2-bc87140ead17.png)

**Comment by bergeson** [comment]
That looks like a huge improvement! So do you add the class in the widget in the "Custom CSS" tab in the module? And do you put ".condensed" or just "condensed" and Divi puts it in properly?
